### ISSUE TITLE
Share a content to Quarrel

### ISSUE THREAD

**Issue by MarcAnt01** [UWPCommunity/Quarrel#109] opened 2019-12-27 10:26 UTC
At the moment it's not possible share a content from an app to Quarrel

**Comment by Avid29** [comment] 2020-01-13 19:27
Duplicate of #108

**Comment by MarcAnt01** [comment] 2020-01-13 19:28
> Duplicate of #108

No, that issue is sharing FROM this one is sharing TO

**Comment by Avid29** [comment] 2020-01-13 19:28
Got it

**Comment by Avid29** [comment] 2020-01-13 19:29
Or you changed the other one. I prefer it like that. Reclosing...

**Closed by Avid29** 2020-01-13 19:29 UTC
Labels: enhancement, rewrite

**Comment by MarcAnt01** [comment] 2020-01-13 19:34
> Or you changed the other one. I prefer it like that. Reclosing...

@matthew4850 has done that.

Anyway, I'll edit the other issue to be meant like you prefer
