### ISSUE TITLE
When adding an attachment, "All Files" only displays images

### ISSUE THREAD

**Issue by Calman102** [UWPCommunity/Quarrel#485] opened 2020-07-24 05:28 UTC
Not sure if this is a bug or intentional, but you can manually type in the name of other files in the "Open" dialogue and they will upload fine (the image preview will be empty though). Would be easier to upload them if "All Files" just displayed, as it suggests, all the files in a folder.

**Comment by Waddle-Doo** [comment] 2020-07-29 17:10
This is a duplicate of #444, however I'll rename that issue to better clarify what's going on there so these can be merged.

**Closed as completed** 2022-04-05 17:00 UTC
Labels: old
