### ISSUE TITLE
Send friend request and send message isn't working from account info dialog

### ISSUE THREAD

**Issue by jaigak** [UWPCommunity/Quarrel#496] opened 2020-08-13 04:21 UTC

**Comment by Waddle-Doo** [comment] 2020-08-13 13:22
This is a duplicate of #376 , which was linked to and closed in #447 and merged into Insider 20.7.15. This can be closed.

**Comment by Waddle-Doo** [comment] 2020-08-13 13:29
I request kindly that you provide longer, more concise descriptions of issues, always check the open and closed issues to make sure your report isn't a duplicate, and always be testing on the latest build of Quarrel Insider. I think the devs and other contributors would really appreciate it, it'd make life much easier.

Thanks! <3

**Closed as completed** 2020-08-14 02:03 UTC
Labels: old
