### ISSUE TITLE
Leaving servers 

### ISSUE THREAD

**Issue by TigerNotice** [UWPCommunity/Quarrel#355] opened 2020-06-16 12:38 UTC
Hello. Ive got another issue.
So I'm trying to leave servers and I click "Leave server" and nothing is happening. This can get frustrating because they're always giving me notifications every so often.

Hope you can fix the issue,
Cal.

**Comment by Waddle-Doo** [comment] 2020-06-23 19:39
I'm just a tester and have no authority on this, but a full week has passed since this was reported and neither me or any of the repo owners have had any success reproducing this. I personally believe this issue can be closed.

**Comment by Waddle-Doo** [comment] 2020-08-28 20:26
This should be closed as the issue is outdated, vague, unsubstantiated, and unreproduceable.

**Closed as completed** 2022-04-05 17:02 UTC
Labels: bug, old
