### ISSUE TITLE
|Xbox| Unable to start up on both Insider and Regular Quarrel

### ISSUE THREAD

**Issue by D181t1z3d** [UWPCommunity/Quarrel#397] opened 2020-06-26 23:44 UTC
So, currently, I am having a bit of trouble strating up Quarel on either the I(nsider) app or the R(egular) app. Whenever I try to boot it up on I app, it tries loading up but crashes. And on the R app, it states that "Quarrel ran into an issue that it couldn't handle" with the bottom text saying "NoMatch". Mind you, I'm using the Xbox version, I have no idea if PC suffers this as well. If someone has run into this issue and has found a resolution, please notify me.

Have a great day, thank you for your time
-D181t1z3d

**Comment by matthew4850** [comment] 2020-06-26 23:47
> So, currently, I am having a bit of trouble strating up Quarel on either the I(nsider) app or the R(egular) app. Whenever I try to boot it up on I app, it tries loading up but crashes. And on the R app, it states that "Quarrel ran into an issue that it couldn't handle" with the bottom text saying "NoMatch". Mind you, I'm using the Xbox version, I have no idea if PC suffers this as well. If someone has run into this issue and has found a resolution, please notify me.
> 
> Have a great day, thank you for your time
> -D181t1z3d

Do you have a computer or windows mobile device you could test this on to see if you experience the same issue?
Also is this immediately on load? Do you see the loading screen? Does it get to the friends list page?

**Comment by D181t1z3d** [comment] 2020-06-26 23:48
Two symptoms of this bug is having splash text that does not load, yet the quoted person is, and 9/10 times the privacy policy isn't there.

**Comment by D181t1z3d** [comment] 2020-06-26 23:49
Sadly, no. I don't have any other device to test this on.

**Comment by D181t1z3d** [comment] 2020-06-26 23:50
And yes, I see the loading screen.

**Comment by D181t1z3d** [comment] 2020-06-28 00:43
It still won't work. Please help me.

**Comment by matthew4850** [comment] 2020-06-28 00:46
> It still won't work. Please help me.

I am looking into it although I am not sure what I can do as I have no idea what could be causing this issue.
~~Could you try creating a new account and logging in with it?~~
Edit: I'm fairly sure a new account would work, there is no need to test it.

**Comment by matthew4850** [comment] 2020-06-28 00:48
I could be wrong here but do you happen to be in any servers without channels?

**Comment by D181t1z3d** [comment] 2020-06-28 01:00
Not really, I could be in a server that has been raided. But how does it correlate?

**Comment by matthew4850** [comment] 2020-06-28 01:09
> Not really, I could be in a server that has been raided. But how does it correlate?

Sorry, I got slightly mixed up but the only issue I could find that is caused by NoMatch is one caused when a channels parent cannot be found.

**Comment by D181t1z3d** [comment] 2020-06-28 01:09
So, I have to make a new account?

**Comment by matthew4850** [comment] 2020-06-28 01:14
No, I think this will be fixed in the next update.

**Comment by D181t1z3d** [comment] 2020-06-28 01:18
Thank you so much. I cannot express my gratitude enough.

**Comment by matthew4850** [comment] 2020-06-28 13:11
I am closing this issue as it should be fixed in the most recent build, if not you can reopen it.

**Comment by D181t1z3d** [comment] 2020-06-28 14:08
New issue. It crashes upon loading.

**Comment by matthew4850** [comment] 2020-06-28 14:11
> New issue. It crashes upon loading.

What do you see before it crashes?

**Comment by D181t1z3d** [comment] 2020-06-28 14:13
Nothing. All it did was load and crash.

**Comment by matthew4850** [comment] 2020-06-28 14:13
> Nothing. All it did was load and crash.

Could you uninstall Quarrel then reinstall it.

**Comment by D181t1z3d** [comment] 2020-06-28 14:14
Done that, many times.

**Comment by matthew4850** [comment] 2020-06-28 14:14
> Done that, many times.

You don't even see the loading screen?

**Comment by D181t1z3d** [comment] 2020-06-28 14:16
I had seen the loading screen, but it didn't show any quote. Not even the privacy policy. A few short seconds and it crash.

**Comment by matthew4850** [comment] 2020-06-28 14:22
> I had seen the loading screen, but it didn't show any quote. Not even the privacy policy. A few short seconds and it crash.

That is very weird, I will look into it although I am unsure why this is happening.

**Comment by D181t1z3d** [comment] 2020-06-28 14:26
Thank you for helping me, I know you are very busy and you're taking the time out of your day to help me get back onto Discord/Quarrel. For this, I am grateful.

**Comment by D181t1z3d** [comment] 2020-06-28 21:55
Is the issue still being resolved?

**Comment by Waddle-Doo** [comment] 2020-06-28 23:24
Hi, Grey the unofficial dedicated tester here! I've noticed your issue here and I wanted to let you know I haven't been able to reproduce this problem under any kind of circumstances on any kind of hardware. Could you let me know if you could possibly install Quarrel on another device and get the same results?

**Comment by Waddle-Doo** [comment] 2020-06-28 23:28
Also, please don't send more than one comment in a row unless it's pertinant. You can chat with us in Quarrel's discord if need be, but spamming the devs with comments under issue reports won't bring more attention to your problem and this space needs to be reserved for documentation when possible, not conversation. >~<

**Comment by D181t1z3d** [comment] 2020-06-28 23:42
Thanks for responding. While Quarrel works now, it crashes almost immediately. I appreciate your help, but doing some things to help fix this will do me wonders. Sadly, I haveno other device for they have been taken away for some time.  Also, I do apologize for the mess above, this bug or glitch makes the app unuseable at times and it's the only way for me to communicate with anyone during these times.

**Comment by Waddle-Doo** [comment] 2020-06-28 23:49
I hate having to be blunt but this is an isolated issue afaik, and even though it is an app breaking crash, Adam and Matthew have unreproduceable errors that effect 75% of the userbase, and a massive refactor to be working on, and this kind of stuff takes higher priority. Your issue will be investigated, but expecting a fix within the next hours is extremely unreasonable, and puts alot of strain on devs that already have their hands full. Thanks for understanding. <3

**Comment by matthew4850** [comment] 2020-06-29 00:02
> Thanks for responding. While Quarrel works now, it crashes almost immediately.

Please could you elaborate on this, I'm not entirely sure what you mean.

**Comment by D181t1z3d** [comment] 2020-06-29 16:39
To elaborate, there are two ways for my Quarrel to crash as of now.
1. Crashes after a message is sent. Happens 100%
2. Crashes if the white outline where the Privacy Policy is supposed to be is there. This usually doesn't happen since I mash the A button for outline to go away.

**Comment by matthew4850** [comment] 2020-06-29 16:41
> To elaborate, there are two ways for my Quarrel to crash as of now.
> 
> 1. Crashes after a message is sent. Happens 100%
> 2. Crashes if the white outline where the Privacy Policy is supposed to be is there. This usually doesn't happen since I mash the A button for outline to go away.

Is that when you send a message or when anyone sends one?

**Comment by D181t1z3d** [comment] 2020-06-29 19:16
After I send a message to anyone, I'm unsure of the ladder option.

**Comment by matthew4850** [comment] 2020-06-29 19:23
> After I send a message to anyone, I'm unsure of the ladder option.

Does this happen when you send a message in servers or is it just in DMs?

**Comment by D181t1z3d** [comment] 2020-06-29 20:22
Servers and DMs alike. Merely going into a server cashes a crash too.

**Comment by matthew4850** [comment] 2020-06-29 20:25
> Servers and DMs alike. Merely going into a server cashes a crash too.

Is the crash when sending a message 100% of the time? And does it happen when someone sends a message to you?

**Comment by D181t1z3d** [comment] 2020-06-29 20:29
It only happens when I send it.

**Comment by matthew4850** [comment] 2020-06-29 20:31
> It only happens when I send it.

Could you try to send a message with just an attachment and no text?

**Comment by D181t1z3d** [comment] 2020-06-29 20:42
I can try.
Edit: It will not let me send any attachments.

**Closed as completed** 2022-04-05 17:02 UTC
Labels: bug, old
